name: Publish to GitHub Package Registry

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run rollup
      - name: Authenticate with GitHub Package Registry
        run: echo "//npm.pkg.github.com/martincivan/esvk_web_lib_idsk3_core:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: Publish package
        run: npm publish --registry=https://npm.pkg.github.com/martincivan/esvk_web_lib_idsk3_core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}